### ISSUE TITLE
Complete

### ISSUE THREAD

**Issue by DoktorDuckyy** [First-Coder/TS3-Control#1]
Hi,
will this project be finished or is stopped or paused. And if it is in processing how is the status

Jonas

**Comment by lgund** [comment]
Currently we are working on this project. If you have special questions above the project you can write them here or in our forum @ https://forum.first-coder.de/

**Comment by Jpofin** [comment]
Yep kinda waiting for the nice web interface for the ts3audiobot aswell :c
